# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e8c5f1a07d3f569bfb27cc08db9d32d5af891d923bcbaa9ef81fd191a6dc4a1190d813daba76ae3ac610a49edf349cb648bd62ab0e034637b14ca9120b52828

test:
  secret_key_base: 35c855d65bdc7e8677c0fb6b69f5ff98bdcd57ff8bea98039fb5fbe9c35a99123f946bc34781506359c285243da856ddd36adcfceac0811419d9b5bad301b24f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
